language: android
jdk: oraclejdk8
sudo: required

env:
  global:
  - GRADLE_OPTS="-Xmx512m"
  matrix:
  - ADB_INSTALL_TIMEOUT=15 ANDROID_BUILD_TOOLS_VERSION=25.0.3 ANDROID_TARGET=android-25 ANDROID_ABI=armeabi-v7a

cache:
  directories:
  - "${TRAVIS_BUILD_DIR}/android/gradle/caches/"
  - "${TRAVIS_BUILD_DIR}/android/gradle/wrapper/dists/"
  - "$HOME/android/.gradle/caches/"
  - "$HOME/android/.gradle/wrapper/"

android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL
  - addon-$ANDROID_TAG-google-$ANDROID_API_LEVEL
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-armeabi-v7a-$ANDROID_TARGET

before_script:
  - chmod +x gradlew

script:
  - ./gradlew build
  - ./gradlew assembleRelease
  # Success or not if a pull request is merged the apk should be updated if it can be build
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./update-apk.sh; fi'

after_success:
  - bash <(curl -s https://codecov.io/bash)

licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

notifications:
  webhooks:

